 # Switches 
set_property PACKAGE_PIN V17 [get_ports {addr[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {addr[0]}] 
set_property PACKAGE_PIN V16 [get_ports {addr[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {addr[1]}] 

# Buttons 
set_property PACKAGE_PIN U18 [get_ports {din[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {din[0]}] 
set_property PACKAGE_PIN T18 [get_ports {din[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {din[1]}] 
set_property PACKAGE_PIN W19 [get_ports {din[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {din[2]}] 
set_property PACKAGE_PIN T17 [get_ports {din[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {din[3]}] 

# LEDs 
set_property PACKAGE_PIN U16 [get_ports dout] 
set_property IOSTANDARD LVCMOS33 [get_ports dout]
#------------------------------------------------------------------------------------------------------------------------------------------
## Switches 
#set_property PACKAGE_PIN V17 [get_ports {addr[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {addr[0]}] 
#set_property PACKAGE_PIN V16 [get_ports {addr[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {addr[1]}] 

## Buttons 
#set_property PACKAGE_PIN U18 [get_ports {din}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {din}] 

## LEDs 
#set_property PACKAGE_PIN U16 [get_ports {dout[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}] 
#set_property PACKAGE_PIN E19 [get_ports {dout[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}] 
#set_property PACKAGE_PIN U19 [get_ports {dout[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {dout[2]}] 
#set_property PACKAGE_PIN V19 [get_ports {dout[3]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {dout[3]}]
#------------------------------------------------------------------------------------------------------------------------------------------
#set_property PACKAGE_PIN V17 [get_ports {x1[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x1[0]}] 
#set_property PACKAGE_PIN V16 [get_ports {x1[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x1[1]}] 
#set_property PACKAGE_PIN W16 [get_ports {x1[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x1[2]}] 


#set_property PACKAGE_PIN V15 [get_ports {x2[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x2[0]}] 
#set_property PACKAGE_PIN W14 [get_ports {x2[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x2[1]}] 
#set_property PACKAGE_PIN W13 [get_ports {x2[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x2[2]}] 

## LEDs 
#set_property PACKAGE_PIN U16 [get_ports {y[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[0]}] 
#set_property PACKAGE_PIN E19 [get_ports {y[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[1]}] 
#set_property PACKAGE_PIN U19 [get_ports {y[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[2]}] 
#set_property PACKAGE_PIN V19 [get_ports {y[3]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[3]}]
#------------------------------------------------------------------------------------------------------------------------------------------
#set_property PACKAGE_PIN V17 [get_ports {x[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x[0]}] 
#set_property PACKAGE_PIN V16 [get_ports {x[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x[1]}] 
#set_property PACKAGE_PIN W16 [get_ports {x[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x[2]}] 
#set_property PACKAGE_PIN W17 [get_ports {x[3]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x[3]}] 
#set_property PACKAGE_PIN W15 [get_ports {x[4]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x[4]}] 
#set_property PACKAGE_PIN V15 [get_ports {x[5]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x[5]}] 
#set_property PACKAGE_PIN W14 [get_ports {x[6]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x[6]}] 

## LEDs 
#set_property PACKAGE_PIN U16 [get_ports {y[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[0]}] 
#set_property PACKAGE_PIN E19 [get_ports {y[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[1]}] 
#set_property PACKAGE_PIN U19 [get_ports {y[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[2]}] 
#set_property PACKAGE_PIN V19 [get_ports {y[3]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[3]}] 
#set_property PACKAGE_PIN W18 [get_ports {y[4]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[4]}] 
#set_property PACKAGE_PIN U15 [get_ports {y[5]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[5]}] 
#set_property PACKAGE_PIN U14 [get_ports {y[6]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[6]}] 
#set_property PACKAGE_PIN V14 [get_ports {y[7]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[7]}]
#------------------------------------------------------------------------------------------------------------------------------------------
#set_property PACKAGE_PIN V17 [get_ports {x[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x[0]}] 
#set_property PACKAGE_PIN V16 [get_ports {x[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x[1]}] 
#set_property PACKAGE_PIN W16 [get_ports {x[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x[2]}] 
#set_property PACKAGE_PIN W17 [get_ports {x[3]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x[3]}] 

## LEDs 
#set_property PACKAGE_PIN U16 [get_ports {y[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[0]}] 
#set_property PACKAGE_PIN E19 [get_ports {y[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[1]}] 
#set_property PACKAGE_PIN U19 [get_ports {y[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[2]}] 
#set_property PACKAGE_PIN V19 [get_ports {y[3]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[3]}] 
#set_property PACKAGE_PIN W18 [get_ports {y[4]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[4]}] 
#set_property PACKAGE_PIN U15 [get_ports {y[5]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[5]}] 
#set_property PACKAGE_PIN U14 [get_ports {y[6]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[6]}] 
#set_property PACKAGE_PIN V14 [get_ports {y[7]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[7]}]
#------------------------------------------------------------------------------------------------------------------------------------------
#set_property PACKAGE_PIN V17 [get_ports {x1[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x1[0]}] 
#set_property PACKAGE_PIN V16 [get_ports {x1[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x1[1]}] 
#set_property PACKAGE_PIN W16 [get_ports {x2[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x2[0]}] 
#set_property PACKAGE_PIN W17 [get_ports {x2[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {x2[1]}] 
##7 segment display 
#set_property PACKAGE_PIN W7 [get_ports {y[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[0]}] 
#set_property PACKAGE_PIN W6 [get_ports {y[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[1]}] 
#set_property PACKAGE_PIN U8 [get_ports {y[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[2]}] 
#set_property PACKAGE_PIN V8 [get_ports {y[3]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[3]}] 
#set_property PACKAGE_PIN U5 [get_ports {y[4]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[4]}] 
#set_property PACKAGE_PIN V5 [get_ports {y[5]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[5]}] 
#set_property PACKAGE_PIN U7 [get_ports {y[6]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {y[6]}] 

#set_property PACKAGE_PIN U2 [get_ports {an[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}] 
#set_property PACKAGE_PIN U4 [get_ports {an[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}] 
#set_property PACKAGE_PIN V4 [get_ports {an[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}] 
#set_property PACKAGE_PIN W4 [get_ports {an[3]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
#------------------------------------------------------------------------------------------------------------------------------------------